/// <reference types="../CTAutocomplete" />
/// <reference lib="es2015" />
// Generated by CT-Pack
import AKBook from "./src/AKBook"
import gitCTCommand from "./src/command"

const f = FileLib.exists(`${Config.modulesFolder}/GitCT/book.txt`)
if (!f) {
    AKBook.display()
    FileLib.write(`${Config.modulesFolder}/GitCT/book.txt`, "true")
}

register("command", gitCTCommand).setName("gitct").setTabCompletions(["help", "import"])